
version: '3.7'

services:
  web:
    build: .
    image: &web web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - './workspace:/workspace'
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:12.0-alpine 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.dev
  pgadmin:
    image: dpage/pgadmin4
    volumes: 
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    env_file: .env.dev
    depends_on:
      - db
  rabbitmq:
    image: "rabbitmq:3"
    env_file: .env.dev
  celery:
    build: .
    image: *web
    command: celery -A e_commerce worker -l info
    volumes:
      - .:/home/app/web
    depends_on:
      - db
      - rabbitmq
    env_file: .env.dev
  nginx:
    build: ./nginx
    env_file: .env.dev
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  pgadmin:

